name: Tag Major Version

on:
  push:
    tags: [v*.*.*]

permissions:
  contents: write

jobs:
  update-major-version-tag:
    name: Update major version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get major version
        id: major-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          echo "sha=$(git rev-list -n 1 $VERSION)" >> $GITHUB_OUTPUT
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "exists=$( [ ! -z $(git tag -l "$MAJOR") ] && echo 1 || echo 0)" >> $GITHUB_OUTPUT

      - name: Create major version tag
        if: steps.major-version.outputs.exists == '0'
        uses: actions/github-script@v7
        with:
          script: |
            await octokit.rest.git.createRef({
              ...context.repo,
              ref: "refs/tags/${{ steps.major-version.outputs.major }}",
              sha: "${{ steps.major-version.outputs.sha }}"
            })

      - name: Move major version tag
        if: steps.major-version.outputs.exists == '1'
        uses: actions/github-script@v7
        with:
          script: |
            await octokit.rest.git.updateRef({
              ...context.repo,
              ref: "refs/tags/${{ steps.major-version.outputs.major }}",
              sha: "${{ steps.major-version.outputs.sha }}",
              force: true
            })
